### ISSUE TITLE
help help kid。。

### ISSUE THREAD

**Issue by SakuraMaiii** [ggerganov/ggml#1010]
I'm sorry if this isn't exactly a question; I'm a beginner and have been thinking about this for a long time but couldn't figure it out. In the file **examples/simple/simple-ctx.cpp**, I'm trying to understand the syntax of **ggml_init**. Specifically, in the following code:

```
if (!is_first_call) {
    // initialize time system (required on Windows)
    ggml_time_init();

    for (int i = 0; i < (1 << 16); ++i) {
        union {
            uint16_t u16;
            ggml_fp16_t fp16;
        } u = {i};
        ggml_table_f32_f16[i] = GGML_COMPUTE_FP16_TO_FP32(u.fp16);
    }
    is_first_call = true;
}
```
The line:
`ggml_table_f32_f16[i] = GGML_COMPUTE_FP16_TO_FP32(u.fp16);`

Why does it jump to the function **ggml_lookup_fp16_to_fp32** instead of the generic function:

`static inline float ggml_compute_fp16_to_fp32(ggml_fp16_t h);`

My computer configuration does not support F16,and it's a very low-end setup (INTEL N5095).

**Comment by slaren** [comment]
The exact definition of `GGML_COMPUTE_FP16_TO_FP32` varies depending on the system hardware, but it is never `ggml_lookup_fp16_to_fp32`.

**Comment by SakuraMaiii** [comment]
> The exact definition of `GGML_COMPUTE_FP16_TO_FP32` varies depending on the system hardware, but it is never `ggml_lookup_fp16_to_fp32`.

Thank you for your response. I added some debugging messages in ggml_lookup_fp16_to_fp32:
```
inline static float ggml_lookup_fp16_to_fp32(ggml_fp16_t f) {
#pragma message("Entering ggml_lookup_fp16_to_fp32")    
    printf("Entering ggml_lookup_fp16_to_fp32");
    uint16_t s;
    memcpy(&s, &f, sizeof(uint16_t));
    return ggml_table_f32_f16[s];
}
```

When I compile using CMake, I see the message "**Entering ggml_lookup_fp16_to_fp32**" during compilation, and I also see "**Entering ggml_lookup_fp16_to_fp32**" printed when running the executable.

However, you mentioned that `GGML_COMPUTE_FP16_TO_FP32` would never be` ggml_lookup_fp16_to_fp32`. Could you please explain why this is the case?
![d215ca7edc49fe2c75aca501e070cb4](https://github.com/user-attachments/assets/231b98c3-ee7d-49a1-8064-fccc7e89649d)

**Comment by slaren** [comment]
After the lookup table is initialized, other code may use it with `GGML_FP16_TO_FP32`. However `GGML_COMPUTE_FP16_TO_FP32` always computes the result without using a lookup table.

**Comment by SakuraMaiii** [comment]
> After the lookup table is initialized, other code may use it with `GGML_FP16_TO_FP32`. However `GGML_COMPUTE_FP16_TO_FP32` always computes the result without using a lookup table.

Thanks for your response. I also added some debugging to` ggml_compute_fp16_to_fp32`:
```
static inline float ggml_compute_fp16_to_fp32(ggml_fp16_t h) {
    printf("Entering ggml_compute_fp16_to_fp32");
```
![20241108203606](https://github.com/user-attachments/assets/912bb4c8-63cd-4be1-903e-bfafdb7522d0)

And it also printed the message. You are a true genius and hero!
