### ISSUE TITLE
GPT-J: Incomplete response

### ISSUE THREAD

**Issue by aaambrosio** [ggerganov/ggml#103]
I'm running gpt-j with [ggml-gpt4all-j](https://gpt4all.io/models/ggml-gpt4all-j.bin) model. Responses are incomplete:

`./bin/gpt-j -m ggml-gpt4all-j.bin -p "Write an essay about a pet dog named Nubi"`
![Screenshot 2023-04-23 at 2 51 57 PM](https://user-images.githubusercontent.com/41741367/233824757-24ba1617-a8f0-4f4c-b029-20e979ee0f95.png)

Am I missing something?

**Comment by aaambrosio** [comment]
Tried using 6B model from [https://huggingface.co/ggerganov/ggml](https://huggingface.co/ggerganov/ggml). Same, incomplete responses.

**Comment by ggerganov** [comment]
Use the `-n` argument

**Comment by aaambrosio** [comment]
> Use the `-n` argument

It worked!

`./bin/gpt-j -n 512 -m ggml-gpt4all-j.bin -p "Write an essay about a pet dog named Nubi"`
![Screenshot 2023-04-23 at 4 26 04 PM](https://user-images.githubusercontent.com/41741367/233828700-0578e9d6-232d-4665-a80a-8ae8131d4437.png)


Thanks a lot 🙇
