### ISSUE TITLE
Are there plans to develop CONV_2D? this is also a VIP 

### ISSUE THREAD

**Issue by Rane2021** [ggerganov/ggml#106]

**Comment by narain1** [comment]
its already in development have a look at this #74

**Comment by ggerganov** [comment]
#74 is not in a working condition yet.
I will get back to this soon and add CONV_2D operator

**Comment by Rane2021** [comment]
great work! expecting!

**Comment by monatis** [comment]
Hi, is this planned for any time soon, or should I give it a try myself? I want to implement `clip.cpp` as CLIP is frequently used in large multimodal models, and this seems to be the only blocker.

**Comment by ggerganov** [comment]
Please go ahead

This is planned, but there are a few high-priority things that will probably take me a week before I get back to this.
Note that currently we have a very limited support for operators with more than 2 arguments, so for `CONV_1D` I implemented a couple of hard-coded calls with fixed padding and stride:

https://github.com/ggerganov/ggml/blob/94a24c9de987fa7a551310a8ba4286e7715d8950/include/ggml/ggml.h#L708-L721

Either follow the same pattern, or if you need a more general-purpose `CONV_2D`, see how we pass extra parameters for example in `ggml_rope()` and do the same thing:

https://github.com/ggerganov/ggml/blob/94a24c9de987fa7a551310a8ba4286e7715d8950/include/ggml/ggml.h#L687-L699

**Comment by monatis** [comment]
Thanks for the hints and pointing me to the right direction! Let's see what I can achieve with it.

**Comment by YavorGIvanov** [comment]
I think [conv_2d](https://github.com/ggerganov/ggml/blob/08c57df1b98ff94d065c0ee2f42294a5bde6bb7b/src/ggml.c#L6936) has been finished and its interface [generalized](https://github.com/ggerganov/ggml/pull/313). Further optimizations of the operations will be done in a separate issue.
