### ISSUE TITLE
bug in stablelm implementation

### ISSUE THREAD

**Issue by mgrabban** [ggerganov/ggml#125]
Hello,

Do you need the the extra layernorm [here](https://github.com/ggerganov/ggml/blob/5f9f1c1744bcbc70b9fd7857bd5a2fa4a75dddce/examples/stablelm/main.cpp#L541)?

This is probably the bug mentioned in stablelm [readme](https://github.com/ggerganov/ggml/blob/master/examples/stablelm/README.md)

Thanks.

**Comment by mgrabban** [comment]
> Hello,
> 
> Do you need the the extra layernorm [here](https://github.com/ggerganov/ggml/blob/5f9f1c1744bcbc70b9fd7857bd5a2fa4a75dddce/examples/stablelm/main.cpp#L541)?
> 
> This is probably the bug mentioned in stablelm [readme](https://github.com/ggerganov/ggml/blob/master/examples/stablelm/README.md)
> 
> Thanks.

Nevermind, huggingface implementation also uses separate layernorms for attention and FF. So this is not the bug.

**Comment by ggerganov** [comment]
No longer sure that I have a bug.
See my comment here: https://github.com/ggerganov/llama.cpp/issues/1063#issuecomment-1527730562
