### ISSUE TITLE
./bin/stablelm -> invalid quantization type 0 (f32)

### ISSUE THREAD

**Issue by lefnire** [ggerganov/ggml#140]
I followed [examples/stablelm](https://github.com/ggerganov/ggml/tree/master/examples/stablelm) step-by. At the [4-bit part](https://github.com/ggerganov/ggml/tree/master/examples/stablelm#4-bit-integer-quantization-mode), I get the following error:

```shell
stablelm_model_quantize: loading model from './stablelm-base-alpha-3b/ggml-model-f16.bin'
stablelm_model_quantize: n_vocab = 50688
stablelm_model_quantize: n_ctx   = 4096
stablelm_model_quantize: n_embd  = 4096
stablelm_model_quantize: n_head  = 32
stablelm_model_quantize: n_layer = 16
stablelm_model_quantize: ftype   = 1
ggml_common_quantize_0: invalid quantization type 0 (f32)
stablelm_model_quantize: failed to quantize model './stablelm-base-alpha-3b/ggml-model-f16.bin'
main: failed to quantize model from './stablelm-base-alpha-3b/ggml-model-f16.bin'
```

I'm a newb, my guess was that means the stablelm-quantize expected 32 instead of f16, so I tried the same steps but used `python3 ../examples/stablelm/convert-h5-to-ggml.py ./stablelm-base-alpha-3b/ 0` (`0` instead of `1`), but no cigar.

**Comment by ggerganov** [comment]
The README has been updated to reflect the new quantization usage - it should work now
