### ISSUE TITLE
MPT quantize does not include quantization version

### ISSUE THREAD

**Issue by philpax** [ggerganov/ggml#168]
Hi there!

The concept of quantization versions was recently introduced by this commit, which encodes the version in the model's `ftype`: https://github.com/ggerganov/ggml/commit/effcfa62da543e71affe6c39b78d0064f0c5d71d

However, it looks like this change didn't make it over to the MPT quantizer:

https://github.com/ggerganov/ggml/blob/2a75bd43113702fe096c75408b300d106be90a58/examples/mpt/quantize.cpp#L89

This means that the MPT models recently uploaded by @TheBloke at https://huggingface.co/TheBloke/MPT-7B-GGML unfortunately do not include the quantization version. The effect of this is mitigated by the MPT example not currently checking the version.

We're checking the version in [llm](https://github.com/rustformers/llm), which is why this has come up. We may add an option to disable the check or override the perceived version, but I figured that it was worth reporting upstream before it proliferates.

**Comment by TheBloke** [comment]
Thanks for the heads up. I'm happy to re do them with the fixed quantization code.

**Comment by TheBloke** [comment]
Going to bed now but I'll look at it tomorrow

**Comment by lukasmoellerch** [comment]
Yes, this was merged while I was working on the mpt model integration - I'll contribute a fix

**Comment by philpax** [comment]
Also worth noting is the code that loads the model needs to account for this (e.g. it needs to modulo the ftype by `GGML_QNT_VERSION_FACTOR`)

**Comment by marella** [comment]
@lukasmoellerch I sent #165 to remove global variables. Can you also please include those changes in your fix.

Also `max_seq_len` is read from model file but doesn't seem to be used anywhere. Is that expected or is it supposed to be used as `n_ctx`?

**Comment by ggerganov** [comment]
Added quantization version support to MPT and Replit models

**Comment by TheBloke** [comment]
Thanks very much for the fix. I've updated my three repos:
https://huggingface.co/TheBloke/MPT-7B-GGML
https://huggingface.co/TheBloke/MPT-7B-Instruct-GGML
https://huggingface.co/TheBloke/MPT-7B-Storywriter-GGML
