### ISSUE TITLE
problem with teknium/Replit-v1-CodeInstruct-3B using example/replit code 

### ISSUE THREAD

**Issue by aseok** [ggerganov/ggml#202]
I've downloaded model and config.json files and running following cmd:
python examples/replit/convert-h5-to-ggml.py models/replit 1
error:
File "examples/replit/convert-h5-to-ggml.py", line 44, in <module>
    tokenizer = AutoTokenizer.from_pretrained(dir_model, trust_remote_code=True)
  File "...python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 721, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.replit.configuration_mpt.MPTConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig,...

**Comment by klosax** [comment]
It looks like replit did some major changes that made the ggml example incompatible with the current model.
HF commit: [Convert ReplitLM to MPT](https://huggingface.co/replit/replit-code-v1-3b/commit/2635241d5b35bf63b8652513c212f645b78b1572)

**Comment by klosax** [comment]
Pr #206 should fix this.

**Comment by aseok** [comment]
Solved according to pr #206 thanks.
