### ISSUE TITLE
Support for starcoder plus and starchat beta

### ISSUE THREAD

**Issue by aseok** [ggerganov/ggml#241]

**Comment by TheBloke** [comment]
This repo already has support for starcoder plus and starchat beta!

I quantised and uploaded them last night, using `/examples/starcoder/convert-hf-to-ggml.py` and `examples/starcoder-quantize` :)

https://huggingface.co/TheBloke/starcoder-GGML
https://huggingface.co/TheBloke/starcoderplus-GGML
https://huggingface.co/TheBloke/starchat-beta-GGML

**Comment by m1chae1bx** [comment]
Hello @TheBloke can you also help quantize https://huggingface.co/VMware/open-llama-7b-open-instruct?

**Comment by TheBloke** [comment]
https://huggingface.co/TheBloke/open-llama-7b-open-instruct-GPTQ
https://huggingface.co/TheBloke/open-llama-7b-open-instruct-GGML

GGML is still uploading as I write this - should all be there in another 15-20 mins or so.
