### ISSUE TITLE
Cannot load `replit-code-v1-3b`

### ISSUE THREAD

**Issue by matthiasgeihs** [ggerganov/ggml#248]
I am using `ggml`@https://github.com/ggerganov/ggml/commit/f52d2a05cf8327baf6c0d49e7b231953179e03d3 and am having trouble loading `replit-code-v1-3b`.

I used `replit/convert-h5-to-ggml.py` to convert to ggml f16.
Also created a q4_0 quantized version using `replit-quantize`.

However, when trying to load either of the models with `replit`
(e.g., `./bin/replit -m replit-code-v1-3b.f16.bin -p "def hello_world():"`)
I get:
```
replit_model_load: unknown tensor 'transformer.blocks.0.norm_1.weight' in model file
main: failed to load model from '/Users/matthias/.cache/ggml/replit-code-v1-3b.f16.bin'
```

Any ideas?

**Comment by apcameron** [comment]
You may need this PR https://github.com/ggerganov/ggml/pull/218

**Comment by matthiasgeihs** [comment]
Works now on https://github.com/ggerganov/ggml/commit/0a63fc0f6cb1915d1fa5c62c8f0f018d072253c9! 👍
