### ISSUE TITLE
ggml : deprecate `GGML_TASK_FINALIZE`

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/ggml#284]
The initial design of the compute tasks in `ggml` was each one to have 3 separate stages:

- `GGML_TASK_INIT`
- `GGML_TASK_COMPUTE`
- `GGML_TASK_FINALIZE`

So far, the `GGML_TASK_FINALIZE` step has been left completely unused and it seems it won't find any applications in the future. Therefore, it is best to remove it all together. This will simplify the code a little bit and also bring performance improvements as there will be fewer thread synchronization points during the graph computation

Related:

- https://github.com/ggerganov/llama.cpp/pull/1556

**Comment by rlanday** [comment]
Hi, I took a look at this and found that GGML_TASK_FINALIZE is used by `ggml_compute_forward_cross_entropy_loss_f32()`:

https://github.com/ggerganov/llama.cpp/blob/178b1850ebd21b349cebbee887950e435c5aa2d3/ggml.c#L15453

Please advise.

**Comment by ggerganov** [comment]
INIT and FINALIZE are now optional and disabled for the majority of ops:

https://github.com/ggerganov/ggml/blob/79ea7a41a388e9e7c85e426e912ab38399c44bfa/src/ggml.c#L4080-L4116

This is good enough for now
