### ISSUE TITLE
Possibly missing type conversions in ggml_set_i32 and ggml_set_f32

### ISSUE THREAD

**Issue by goerch** [ggerganov/ggml#329]
Randomly noticed that `ggml_set_f32`'s signature is

```
struct ggml_tensor * ggml_set_f32(struct ggml_tensor * tensor, float value);
```

and it forwards the `value` without explicit conversion to

```
inline static void ggml_vec_set_f16(const int n, ggml_fp16_t * x, const int32_t v);
```

This doesn't feel right given the existence of GGML_FP32_TO_FP16?

**Comment by ggerganov** [comment]
Good catch - it's a bug
