### ISSUE TITLE
Considering ggml 2D tensors are row major, the comment in ggml.h at line 136 and 138 looks incorrect

### ISSUE THREAD

**Issue by sankalpdayal** [ggerganov/ggml#348]
since nb[0] is stride per element and nb[1] is stride for entire row, an element at index for example row 1 and col 2 will be 1*nb[1] + 2*nb[0]. However the comment nb[0] and nb[1] are swapped. Just wanted to check if I am understanding it correctly.

**Comment by ggerganov** [comment]
Changed the element indices to correspond to the Python convention - hopefully this is less confusing
