### ISSUE TITLE
add /cmp-nct/ggllm.cpp as falcon example in readme.md

### ISSUE THREAD

**Issue by maddes8cht** [ggerganov/ggml#361]
The `Updates`section of the readme.md lists a number of projects that are based on `ggml`.

Falcon is not included so far.
https://github.com/cmp-nct/ggllm.cpp is a very active project with a very powerful implementation of Falcon on Llama.
I think it should be listed in the readme.

**Comment by znsoftm** [comment]
The name confused us.   Maybe another unique name is better :)

**Comment by znsoftm** [comment]
falcon.cpp ?

**Comment by maddes8cht** [comment]
At the moment it is a project that is primarily focused on falcon, but the idea was also to create a basis to more easily integrate different model families - so both llama and falcon and possibly starcoder , mpt etc.
Hence the name ggLLM, not for llama, but for large language model.

**Comment by znsoftm** [comment]
cool.  but ggLMM always confuse me a little bit,  it's like ggml :)
