### ISSUE TITLE
Why add 1024*1024 to ctx_size

### ISSUE THREAD

**Issue by Metal-joker** [ggerganov/ggml#387]
https://github.com/ggerganov/ggml/blob/64d645ab55d461fbf2ce6b331f4fd01d59cdb04c/examples/mnist/main.cpp#L79-L83

new to cpp and ggml, could anyone help me understand this?

**Comment by ggerganov** [comment]
It should be `n_tenors * ggml_tensor_overhead()` instead of `1024*1024`.
But I was just being lazy to count the number of tensor and decided to put a some extra space that should be enough

**Comment by Metal-joker** [comment]
> It should be `n_tenors * ggml_tensor_overhead()` instead of `1024*1024`. But I was just being lazy to count the number of tensor and decided to put a some extra space that should be enough

Thanks man, got it now
