### ISSUE TITLE
Instructions on how to build a wasm ggml.

### ISSUE THREAD

**Issue by fire** [ggerganov/ggml#419]
It sounds obvious that we can compile ggml into wasm with WebGPU or Webgl2 support.

Has anyone done it and written about how to do it?

Alternatively, one can assist with some idea how to do it.

**Comment by fire** [comment]
The information was in the whispher.cpp repo

**Comment by westurner** [comment]
- "Minimal [whisper.cpp](https://github.com/ggerganov/whisper.cpp) example running fully in the browser"
  https://whisper.ggerganov.com/
- https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.wasm :
  > This WASM port utilizes [WASM SIMD 128-bit intrinsics](https://emcc.zcopy.site/docs/porting/simd/) so you have to make sure that [your browser supports them](https://webassembly.org/roadmap/).
  - https://github.com/ggerganov/whisper.cpp/issues/585
  - https://github.com/ggerganov/whisper.cpp/issues/103
    - W3C WebNN
      - Spec: https://w3.org/TR/webnn/
      - Web: https://webmachinelearning.github.io/webnn-intro/
    - WASI-NN
      - Spec: https://github.com/WebAssembly/wasi-nn
  - https://github.com/ggerganov/whisper.cpp/issues/428

**Comment by westurner** [comment]
- examples/Converting_starcoder_model.ipynb: https://github.com/rahuldshetty/starcoder.js/blob/main/examples/Converting_starcoder_model.ipynb
- 
- https://github.com/rahuldshetty/starcoder.js/blob/cfd52a54f1c5224be8ee8524b55b9df4c82d09a5/build.sh#L9C1-L9C380 w/ newlines:
```bash
make \
  CC=emcc \
  CXX=em++ \
  LLAMA_NO_ACCELERATE=1 \
  CFLAGS="\
    -DNDEBUG \
    -s MEMORY64" \
  CXXFLAGS="\
    -DNDEBUG \
    -s MEMORY64" \
  LDFLAGS="\
    -s MEMORY64 \
    -s FORCE_FILESYSTEM=1 \
    -s EXPORT_ES6=1 \
    -s MODULARIZE=1 \
    -s TOTAL_MEMORY=2GB \
    -s STACK_SIZE=524288 \
    -s ALLOW_MEMORY_GROWTH \
    -s EXPORTED_FUNCTIONS=_main \
    -s EXPORTED_RUNTIME_METHODS=callMain \
    -s BUILD_AS_WORKER=1 \
    -s SINGLE_FILE=1 \
    -s NO_EXIT_RUNTIME=1" \
  main.js
```

**Comment by westurner** [comment]
- [ ] ggml, llama.cpp, and whisper.cpp could be built with/by emscripten-forge?

  The existing emscripten-forge package definitions are in emscripten-forge/recipes//recipes/recipes_emscripten:
  https://github.com/emscripten-forge/recipes/tree/main/recipes/recipes_emscripten

**Comment by limcheekin** [comment]
> * [ ]  ggml, llama.cpp, and whisper.cpp could be built with/by emscripten-forge?
>   The existing emscripten-forge package definitions are in emscripten-forge/recipes//recipes/recipes_emscripten:
>   https://github.com/emscripten-forge/recipes/tree/main/recipes/recipes_emscripten

Thanks for sharing. As the issue had been closed, do you found the solution to build llama.cpp to WebAssembly?
