### ISSUE TITLE
ggml_init: Illegal instruction at address 0x<address>

### ISSUE THREAD

**Issue by maihd** [ggerganov/ggml#44]
When build tests/test0.c program, it's crashed when run on Windows compile with `zig cc`. Because in ggml_time_us() `timer_freq` are not inialized. I fixed by adding ggml_time_init().
Src: https://github.com/maihd/fun-with-zig/blob/main/ggml_bindings/src/main.zig

**Comment by ggerganov** [comment]
Would you like to open a PR with this change?

**Comment by maihd** [comment]
OK!
