### ISSUE TITLE
Support for xPos positional embedding

### ISSUE THREAD

**Issue by jploski** [ggerganov/ggml#441]
[xPos](https://arxiv.org/pdf/2212.10554.pdf) is an improved version of the original RoPE from the [RoFormer](https://arxiv.org/pdf/2104.09864.pdf) paper (i.e. a modification of ggml_rope with !is_neox flag). I'm unaware of published models using it yet, but it is important because it's the positional embedding employed by the [RetNet](https://arxiv.org/abs/2307.08621) paper (which offers support for O(1) inference, i.e. independent from context length, with non-degraded quality; a potential superior replacement for attention with kv caches).

For a quick Python comparison of the original RoPE, GPT-NeoX RoPE and xPos RoPE see: https://github.com/jploski/RotaryEmbedding

Based on the above I will create a pull request with an initial (non-CUDA) implementation.

**Comment by jploski** [comment]
PR: https://github.com/ggerganov/ggml/pull/442

**Comment by YavorGIvanov** [comment]
Isn't this done ? Please, reopen if I am wrong.
