### ISSUE TITLE
ggml : add broadcast support for BLAS ggml_mul_mat()

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/ggml#460]
For F16 and F32 CPU matrix multiplications BLAS will likely remain necessary, especially on Apple Silicon where we have Accelerate CBLAS using the AMX coprocessor. So we need to resolve the following TODOs:

https://github.com/ggerganov/ggml/blob/08c57df1b98ff94d065c0ee2f42294a5bde6bb7b/src/ggml.c#L10796-L10799

https://github.com/ggerganov/ggml/blob/08c57df1b98ff94d065c0ee2f42294a5bde6bb7b/src/ggml.c#L10782-L10785

This will fix SAM inference on Apple Silicon: https://github.com/ggerganov/ggml/issues/459

The broadcast logic is implemented in the same function for the non-BLAS branch:

https://github.com/ggerganov/ggml/blob/08c57df1b98ff94d065c0ee2f42294a5bde6bb7b/src/ggml.c#L10905-L10909

Should be simple enough to adapt, but need to make sure it works correctly. Probably the best way to test it is to use the SAM inference example, which works without BLAS but asserts with BLAS.

**Comment by bccw2021** [comment]
Thank you!
