### ISSUE TITLE
How to access the ggml_tensor data?

### ISSUE THREAD

**Issue by MrGrayCode** [ggerganov/ggml#512]
Hi, this may be a silly question but how can I access the data stored in a `ggml_tensor`? For example, in `examples/gpt-2/main.cpp` when I try printing some vector as below I get a segmentation fault:
```
  for (int i = 0; i < 5; ++i) {
      std::cout << ((float*) inpL->data)[i];
  }
```
The above method used to work for me in a previous version of ggml, but do longer works on the current master.

**Comment by Rakesh-dhilip** [comment]
@slaren what if we to manipulate the values in the tensor . like non learnable params.
