### ISSUE TITLE
Error when using ggml_scale

### ISSUE THREAD

**Issue by MrGrayCode** [ggerganov/ggml#517]
I am trying to write an inference script using the ggml library and get the following error when using ggml_scale. 
`GGML_ASSERT: /mnt/d/repos/ggml/src/ggml.c:6197: ggml_is_padded_1d(a)`

In the code the scale operation follows a permute operation and that seems to cause the error:
```
struct ggml_tensor * KQ = ggml_permute(ctx0, ggml_mul_mat(ctx0, Q, K), 1, 0, 2, 3);
struct ggml_tensor * KQ_scaled = ggml_scale(ctx0, KQ, ggml_new_f32(ctx0, 1.0f/(float(n_embd)/n_head)));
```

I tried to fix the error by creating a new copy of `KQ` before applying the scale as:
```
struct ggml_tensor * KQ = ggml_permute(ctx0, ggml_mul_mat(ctx0, Q, K), 1, 0, 2, 3);
struct ggml_tensor * KQ_copy = ggml_cpy(ctx0, KQ, ggml_new_tensor_3d(ctx0, GGML_TYPE_F32, n_past+N, N, n_head));
struct ggml_tensor * KQ_scaled = ggml_scale(ctx0, KQ_copy, ggml_new_f32(ctx0, 1.0f/(float(n_embd)/n_head)));
```
but when I print the values of `KQ_scaled` they are all 0 or close to 0.

I think there might be something wrong with the way I am using these functions. Any help would be appreciated, thanks.

**Comment by YavorGIvanov** [comment]
You will need to use KQ = ggml_cont(ctx0, KQ) and then do ggml_scale(ctx0, KQ, ..). The reason is that the permute operation just creates a view to the tensor argument and only switches its size and offsets. Some operations can work with such non-contiguous tensors by using the offsets (nb[..]), but some can't, so they assert.

**Comment by MrGrayCode** [comment]
@YavorGIvanov thank you for reply. I tried using `ggml_cont` but I am still getting the error that the KQ values after permutation are wrong. 

My code snippet looks like this:
```
struct ggml_tensor * KQ = ggml_cont(ctx0, ggml_permute(ctx0, ggml_mul_mat(ctx0, Q, K), 1, 0, 2, 3));
std::cout << "[DEBUG] KQ: ";
for (int i=0;i<5;++i){
    std::cout << ((float *) KQ)[i] << " ";
 }
std::cout << "\n";
struct ggml_tensor * KQ_scaled = ggml_scale(ctx0, KQ, ggml_new_f32(ctx0, 1.0f/(float(n_embd)/n_head)));
std::cout << "[DEBUG] scale : " << 1.0f/(float(n_embd)/n_head)) << "\n";
std::cout << "[DEBUG] KQ scaled: ";
for (int i=0;i<5;++i){
    std::cout << ((float *) KQ_scaled)[i] << " ";
}
std::cout << "\n";
```
Output:
```
[DEBUG] KQ: 0.355469 0.427734 0.369141 0.376953 0.4375
[DEBUG] scale: 0.0078258
[DEBUG] KQ scaled: 0 0 4.2039e-45 0 1.4013e-45 
```

This is just the first five values, but I tried printing the whole tensor and `KQ_scaled` is completely wrong.

**Comment by YavorGIvanov** [comment]
Sorry for not responding faster. Did you manage to resolve it ?

**Comment by MrGrayCode** [comment]
@YavorGIvanov Yes, I was able to fix it. For some reason my print statements were not in sync with the operations so I was actually looking at old values. But anyway, the whole thing works now. Thanks.
