### ISSUE TITLE
GPT-J broken after transpose changes in ggml_new_tensor_2d

### ISSUE THREAD

**Issue by djinn** [ggerganov/ggml#52]
I am receiving this error when loading GPT-J on AWS Graviton2 EC2 node. 
`gptj_model_load: tensor 'transformer.h.0.mlp.fc_in.weight' has wrong shape in model file: got [4096, 16384], expected [16384, 4096]`

The error seems to be issuing from `ggml_new_tensor_2d` and specifically transpose activity in recently checked in code. Are there any ways to either modify the model or use it as is with current code.

**Comment by ggerganov** [comment]
Sorry about that - I haven't updated the models that I am hosting with the new format.
For now you have to generate the `ggml` models from the original ones yourself by following the instructions.

I'll try to find some time in the next days and update the hosted files - will write here when ready.

**Comment by LostRuins** [comment]
I tried switching back to the old main.cpp example using the new ggml library version, but I am getting `GGML_ASSERT: ggml.c:4250: !ggml_is_transposed(a)`. 

Is there any reason why the new library won't work with the old model + old example cpp? Is there any way I can get it to work without having to update my models?

**Comment by ggerganov** [comment]
The new `ggml` lib deprecated this particular path where the matrix `a` is transposed. This was necessary because this path produced different results for different number of threads, which in certain situations is not desirable.
So I decided to drop it all together.

There is no easy way to go back to the old behaviour.
You will just have to wait for me to reconvert the models and re-upload them to HF.
But it might take me a few days as I am having a hard time managing my disk space with all the models.

**Comment by LostRuins** [comment]
Hmm okay thanks for the reply. Would it then be possible to apply a load-time transposition when reading from the old format?

I disabled the tensor shape checks, then tried manually applying a `ggml_transpose` on load for each layer matching the names `.mlp.fc_in.weight` `.attn.out_proj.weight` `.attn.q_proj.weight` `.attn.k_proj.weight` and `.attn.v_proj.weight` (inside `gptj_model_load` right after ` fin.read(reinterpret_cast<char *>(tensor->data), ggml_nbytes(tensor));`).  

However, while the model loads, it doesn't seem to generate anything correctly (just outputting a bunch of newlines, spaces and dashes). What am I doing wrongly? Is my approach viable? Even after updating to the new formats I'd still like to maintain backward compatibility with old model files if possible.

**Comment by djinn** [comment]
I tested GPT-J model conversion with available tooling. It worked seamlessly. Thanks.

**Comment by pikalover6** [comment]
> I tested GPT-J model conversion with available tooling. It worked seamlessly. Thanks.

Could you possibly upload it to hf?  I don't seem to have enough ram to run the conversion.

**Comment by djinn** [comment]
Done. https://huggingface.co/djinnn/ggml-gpt-j/tree/main

**Comment by LostRuins** [comment]
@djinn why is it 22gb compressed? Is it quantized / fp16?

**Comment by djinn** [comment]
I uploaded fp32 version. It is better to start with higher precision model and quantise based on requirement. Not sure though  what is RAM requirement for reduction in precision. If quantisation and fp16 conversion is expensive, I can upload fp16 version too.

**Comment by ahakanbaba** [comment]
You can use the files from here. 
https://huggingface.co/hakanbaba/ggml-gpt-j-6b/tree/main

**Comment by ggerganov** [comment]
The HF repo with `ggml` models has been updated - both GPT-2 and GPT-J can be downloaded now that are compatible with latest `master`:

https://huggingface.co/ggerganov/ggml/tree/main

**Comment by morpheus2448** [comment]
Hi. I downloaded the ggml-model-gpt-2-1558M.bin from https://huggingface.co/ggerganov/ggml/tree/main this morning.
I cloned the github and compiled binaries.
I get the 'failed to load' message. The 774M model works fine.

774M model:
```
[morpheus@zion bin]$ ./gpt-2 -m /home/morpheus/.local/share/containers/storage/volumes/weights/_data/ggml-model-gpt-2-774M.bin -p "This is a fine example of"
main: seed = 1682519650
gpt2_model_load: loading model from '/home/morpheus/.local/share/containers/storage/volumes/weights/_data/ggml-model-gpt-2-774M.bin'
gpt2_model_load: n_vocab = 50257
gpt2_model_load: n_ctx   = 1024
gpt2_model_load: n_embd  = 1280
gpt2_model_load: n_head  = 20
gpt2_model_load: n_layer = 36
gpt2_model_load: f16     = 1
gpt2_model_load: ggml ctx size = 1962.80 MB
gpt2_model_load: memory size =   360.00 MB, n_mem = 36864
gpt2_model_load: model size  =  1479.99 MB
main: prompt: 'This is a fine example of'
main: number of tokens in prompt = 6, first 8 tokens: 1212 318 257 3734 1672 286 

This is a fine example of a situation where a great writer was able to tell a story in a way that makes it seem fresh, and in a way that is both accessible to a wide audience and timeless. It's hard to imagine any other novel in the last quarter of the 20th century that could make us feel like we were watching a new master at work, and it's hard to imagine any other novel that would have the same impact on readers as this one.<|endoftext|>

main: mem per token =  9026972 bytes
main:     load time =   717.63 ms
main:   sample time =    38.80 ms
main:  predict time =  7598.98 ms / 79.99 ms per token
main:    total time =  8575.01 ms
```
1558M model:
```
[morpheus@zion bin]$ ./gpt-2 -m /home/morpheus/.local/share/containers/storage/volumes/weights/_data/ggml-model-gpt-2-1558M.bin -p "This is a fine example of"
main: seed = 1682519799
gpt2_model_load: loading model from '/home/morpheus/.local/share/containers/storage/volumes/weights/_data/ggml-model-gpt-2-1558M.bin'
gpt2_model_load: failed to open '/home/morpheus/.local/share/containers/storage/volumes/weights/_data/ggml-model-gpt-2-1558M.bin'
main: failed to load model from '/home/morpheus/.local/share/containers/storage/volumes/weights/_data/ggml-model-gpt-2-1558M.bin'
```

Thanks.

**Comment by ggerganov** [comment]
Can you confirm the SHA sum?

```
$ ▶ sha256sum build-release/models/gpt-2-1558M/ggml-model-f16.bin 
e60f9c48e69af4dca841038388ab50bf1e0ef2c816abde4c7ce28d75485ce16e  build-release/models/gpt-2-1558M/ggml-model-f16.bin
```
