### ISSUE TITLE
Question about ggml-alloc assert in CPU ggml-backend version of Sam.cpp 

### ISSUE THREAD

**Issue by YavorGIvanov** [ggerganov/ggml#561]
I started using the the ggml-backend API in Sam.cpp.
After this commit - https://github.com/ggerganov/ggml/pull/547/commits/25ce18aecb32a4a5078839f77b70799ba323c7c8 I hit an assert in Debug. The reason is that the view in init_view(..) doesn't have a valid buffer as the view_src also doesn't. I disabled the assert in this case here -> https://github.com/YavorGIvanov/ggml/commit/94a4c07c0e7a41d8929684f969ee86d6ca409c84 and everything works fine.

Does that point to an underlying problem in the Sam implementation or not ? (I know that potentially the CUDA version won't work, but currently SAM.cpp doesn't support CUDA)

**Comment by slaren** [comment]
It is a bug, it also affects llama.cpp. Your fix looks good.

**Comment by YavorGIvanov** [comment]
Ok. Should I make a simple PR or you would address it as part of some other changes ?

**Comment by slaren** [comment]
We should fix this as soon as possible, a PR would be great.

**Comment by YavorGIvanov** [comment]
https://github.com/ggerganov/ggml/pull/562

**Comment by ggerganov** [comment]
Thank you @YavorGIvanov
