### ISSUE TITLE
Unable to attach with GDB when hitting GGML_ASSERT after backend v2 changes

### ISSUE THREAD

**Issue by YavorGIvanov** [ggerganov/ggml#630]
I use VS Code to debug a program through the Remote - SSH plugin with GDB. After this change:
![image](https://github.com/ggerganov/ggml/assets/8558655/23d15df4-bf19-4590-b026-595c00bd0cc7)

made in this PR https://github.com/ggerganov/ggml/pull/586 I am getting the bellow message, when I hit a ggml assert and gdb is unable to attach to the process. 
```
GGML_ASSERT: /path/ggml/src/ggml-backend.c:56: false
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
warning: process 30496 is already traced by process 30490
ptrace: Operation not permitted.
No stack.
```

If I replace ggml_print_backtrace(); with abort() it works as before (attaching with gdb as expected)

**Comment by slaren** [comment]
Does this cause any issues? It's just meant to show a backtrace as a debugging aid, it is ok if in some cases it cannot be shown.

**Comment by YavorGIvanov** [comment]
The only issue was that the debugger didn't stop and let me expected the progrma state due to the missing abort() call. As you mention that exit is replaced with abort in llama.cpp -> I am closing this.

**Comment by ggerganov** [comment]
Will likely sync after #625 is merged
