### ISSUE TITLE
why add 512 : ggml_backend_alloc_buffer(backend_kv, memory_size + 512*2);

### ISSUE THREAD

**Issue by EveningLin** [ggerganov/ggml#637]
![image](https://github.com/ggerganov/ggml/assets/110521494/a3da7d64-d9d0-4782-b927-14c881ed8c21)
![image](https://github.com/ggerganov/ggml/assets/110521494/46c6d9d3-f811-4284-b005-b0d51851c8a0)

I don't understand why 512 needs to be added, but it looks like a routine operation. May I ask what it aims at？

**Comment by ggerganov** [comment]
The `ggml_context` contains the "meta" information for each tensor - this is the `ggml_tensor` struct. It can also optionally contain the tensor data, if the `ggml_context` is created with `.no_alloc = false`.

The `512` were the old way to account for the size overhead of the meta information.
Today, you should use the dedicated `ggml_tensor_overhead()` and `ggml_graph_overhead()` functions for that. Here is an example:

https://github.com/ggerganov/ggml/blob/1f6c60de15d207ffb892941c01ed98249ca62bf7/examples/gpt-2/main.cpp#L556-L560

The code in the first screenshot that you posted should be rewritten like this:

```c++
// old
model.buffer_kv = ggml_backend_alloc_buffer(backend_kv, memory_size + 512*2);

// new
model.buffer_kv = ggml_backend_alloc_buffer(backend_kv, memory_size + 2*ggml_tensor_overhead());
```

The `backend_kv` context contains 2 tensors:
- the total data size of the 2 tensors is `memory_size`
- the overhead from their meta information is `2*ggml_tensor_overhead()`

In some case, you can create the `ggml_context` with `.no_alloc = true`. In these cases, the `ggml_context` will contain only the meta information without the tensor data. So the buffer size in the example above would be just:

```c++
model.buffer_kv = ggml_backend_alloc_buffer(backend_kv, 2*ggml_tensor_overhead());
```

**Comment by EveningLin** [comment]
thank all of you for answering my questions ! i am also confused hahaha
`model.buffer_kv = ggml_backend_alloc_buffer(backend_kv, 2*ggml_tensor_overhead());`It is an incorrect way of expression？？
can 512 be replaced by ggml_tensor_overhead?
512 is just an estimate of the memory used to solve alignment and other issues？？
