### ISSUE TITLE
"array size is too large" on model load

### ISSUE THREAD

**Issue by iamlemec** [ggerganov/ggml#714]
I think the bounds check in the recent commit #709 is backwards, specifically at

https://github.com/ggerganov/ggml/blob/b2a5c34073e68b841568b2787ed5d15ae6a8d475/src/ggml.c#L19438

and the one before it. I'm getting "array size is too large" when trying to load a model with the vocab list included.

**Comment by ggerganov** [comment]
Sorry about that - will fix it in a bit
