### ISSUE TITLE
ggml : make ggml_fp16_t private

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/ggml#720]
Currently the `ggml_fp16_t` typedef is exposed in the public API:

https://github.com/ggerganov/ggml/blob/6b14d738d9100c50c199a3b1aaa960f633904476/include/ggml/ggml.h#L317-L332

Since this type is platform specific, it would make sense to hide it by moving it in `ggml-impl.h`.
We will still expose an API for F16 <-> F32 conversions, but it sill operate on `void *` instead of `ggml_fp16_t`

**Comment by slaren** [comment]
We could probably define it to `uint16_t` always, and only cast it to `__fp16` in the ARM code that can take advantage of that. The CUDA one is weird, it should only be used when compiling `ggml-cuda.cu`, which never uses this type anyway.

**Comment by ggerganov** [comment]
Ah yes, doing so would make this change much simpler
