### ISSUE TITLE
Incorrect Error Handling in ggml_backend_graph_compute Function in example/magika/main.cpp

### ISSUE THREAD

**Issue by charloco** [ggerganov/ggml#760]
**Describe the bug**
There seems to be an error in the error handling logic of the `ggml_backend_graph_compute` function. The function returns a status code of 0 when it executes successfully. However, the current logic treats a successful execution as an error due to the use of the logical NOT operator (`!`).

**To Reproduce**
Here is the problematic code snippet:

```c
if (!ggml_backend_graph_compute(model.backend, gf)) {
    fprintf(stderr, "%s: ggml_backend_graph_compute() failed\n", __func__);
    return false;
}
```

**Expected behavior** The if condition should not be negated. The correct code should be:
```
if (ggml_backend_graph_compute(model.backend, gf) != GGML_STATUS_SUCCESS) {
    fprintf(stderr, "%s: ggml_backend_graph_compute() failed\n", __func__);
    return false;
}
```

**Comment by slaren** [comment]
Should be fixed now, thanks.
