### ISSUE TITLE
Add Qualcomm mobile SoC native backend for GGML

### ISSUE THREAD

**Issue by zhouwg** [ggerganov/ggml#771]
1. Apple's dedicated machine learning acceleration library(ANE) is very important for GGML/llama.cpp's performance on iOS/Mac

we should/might study something about [Qualcomm's dedicated/proprietary machine learning acceleration library](https://developer.qualcomm.com/software/qualcomm-neural-processing-sdk) accordingly.

![Screenshot from 2024-03-10 21-57-20](https://github.com/cdeos/kantv/assets/6889919/ad714528-0f7a-49a2-898e-4ae0da03864f)

2. background:

<ul>

<li>
<a href="https://github.com/zhouwg/ggml/tree/master/examples/simple">simple backend</a>
</li>
<li>
Opinions about template based GEMM kernels

https://github.com/ggerganov/llama.cpp/discussions/3965

![Screenshot from 2024-03-25 15-05-59](https://github.com/ggerganov/ggml/assets/6889919/d1c78382-fe83-45d8-9b10-9b4c469f3e8f)

</li>

<li>
Add GPU support to ggml

https://github.com/ggerganov/llama.cpp/discussions/915
</li>

</ul>

3. A small R&D team from Intel China branch in Shanghai has provided ggml with the sycl native backend based on Intel chips.

<ul>

<li>
Adding Native Support of SYCL for Intel GPUs

https://github.com/ggerganov/llama.cpp/issues/4749

</li>

<li>
SYCL backend support Multi-card 

https://github.com/ggerganov/llama.cpp/issues/5282
</li>

</ul>

**Comment by zhouwg** [comment]
It seems done and now is PR stage.

so I'd like to close this opening issue accordingly.

**Comment by ZodiacFRA** [comment]
@zhouwg Thanks for you work :) Has the PR been merged? I cannot find QNN in the llama.cpp nor whisper.cpp supported backend list
