### ISSUE TITLE
doc: lack of official logo of GGML

### ISSUE THREAD

**Issue by zhouwg** [ggerganov/ggml#776]
An official logo for whisper.cpp already exists

![235238348-05d0f6a4-da44-4900-a1de-d0707e75b763](https://github.com/ggerganov/ggml/assets/6889919/3161ef9a-a322-43e5-93aa-94d723798738)

An official logo for llama.cpp already exists
![230134379-7181e485-c521-4d23-a0d6-f7b3b61ba524](https://github.com/ggerganov/ggml/assets/6889919/25419d28-1dfc-4af6-941a-47e3f25d67ae)

it seems there is lack of official logo of GGML

**Comment by Green-Sky** [comment]
maybe we can ask HF if we can lean on their icon for ggml/gguf.


(it's an embedded svg, so here is a screen cap)
![image](https://github.com/ggerganov/ggml/assets/2938071/ccf89551-4e82-4e3a-917c-c38bc41ab81f)

**Comment by zhouwg** [comment]
> maybe we can ask HF if we can lean on their icon for ggml/gguf.
> 
> (it's an embedded svg, so here is a screen cap) ![image](https://private-user-images.githubusercontent.com/2938071/318189932-ccf89551-4e82-4e3a-917c-c38bc41ab81f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDU5MzQsIm5iZiI6MTcxMTgwNTYzNCwicGF0aCI6Ii8yOTM4MDcxLzMxODE4OTkzMi1jY2Y4OTU1MS00ZTgyLTRlM2EtOTE3Yy1jMzhiYzQxYWI4MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMTMzMzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDlmNjM0ZTdmZjBjYjk2ZjM1YzZhNTY4YmIxMDg3NzRjZWMzNGE0YjM2ZDUyNmQyYjY4YzVjYWE3NDcxZDE4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z_LtknqiDX21JmNeAMwh4GIHGd03S1KrVMSGiOD719k)

thanks.

**Comment by julien-c** [comment]
happy to provide a SVG or any other file format export it it's useful (cc: @gary149)

**Comment by zhouwg** [comment]
thanks so much.

![1262794297](https://github.com/ggerganov/ggml/assets/6889919/9949c68b-f6ea-4666-b231-425aa9e21b1d)
