### ISSUE TITLE
Setting tensor's backend

### ISSUE THREAD

**Issue by rgerganov** [ggerganov/ggml#779]
After recent CUDA [refactoring](https://github.com/ggerganov/ggml/commit/c5b64b2aa7dcc873a255caa57ecbf1e5cf4de603), we no longer set `GGML_BACKEND_TYPE_GPU` in `ggml_backend_cuda_buffer_init_tensor()` and tensors end up with `GGML_BACKEND_TYPE_CPU` backend even when using CUDA.

Is this a bug or part of a bigger plan which removes the `backend` property of the tensors?

**Comment by slaren** [comment]
The goal is to remove `backend` from the tensor entirely. Backends can use the buffer type to identify the storage location of the tensors instead. I think that at this point, only the OpenCL backend depends on the value of the `backend` property.

**Comment by rgerganov** [comment]
Thanks. That confirms my assumption.
