### ISSUE TITLE
Is there interest in a cuda implementation for ggml_conv_1d

### ISSUE THREAD

**Issue by balisujohn** [ggerganov/ggml#788]
Unless I'm missing something ggml doesn't support it. It looks like I'm going to need it for tortoise.cpp. Is there interest in a cuda implementation for `ggml_conv_1d` being upstreamed into ggml?

**Comment by slaren** [comment]
I think `ggml_conv_1d` is already supported in CUDA via im2col. Did you have any issues with it?

**Comment by balisujohn** [comment]
ah, I'll look into that, and determine if there's features missing that I need.

**Comment by balisujohn** [comment]
I ported to the newest version of ggml and the op worked correctly. Closing this issue
