### ISSUE TITLE
Add dsp backend in ggml.h

### ISSUE THREAD

**Issue by zhouwg** [ggerganov/ggml#794]
could a dsp backend be added in this file for fix an opening issue #771?

GGML_BACKEND_TYPE_DSP = 30,

https://github.com/ggerganov/ggml/blob/master/include/ggml/ggml.h#L385

**Comment by slaren** [comment]
The aim is to remove `ggml_tensor::backend`, so we do not want to add to it. New backends should use the buffer type to identify the location of a tensor.

**Comment by zhouwg** [comment]
thanks. I see.
