### ISSUE TITLE
License for Python-based GGUF parser with NumPy vectorization

### ISSUE THREAD

**Issue by 99991** [ggerganov/ggml#802]
I have implemented a Python-based parser for GGUF with NumPy vectorization and was not sure in how far it should be considered a derivative work, since the implementation is substantially different, but of course the data layout has to be the same. Compare e.g. dequantize_row_q3_K

https://github.com/ggerganov/ggml/blob/fca1caafea7de9fbd7efc733b9818f9cf2da3050/src/ggml-quants.c#L1723C32-L1723C42

with dequantize_q3_k

https://github.com/99991/pygguf/blob/ce1dcea6ff189e3d83b62f5604e6f4d2de548a4d/gguf.py#L141

Anyway, I just wanted to ask you if you are alright with this license, or if I should change anything.

https://github.com/99991/pygguf/blob/ce1dcea6ff189e3d83b62f5604e6f4d2de548a4d/LICENSE#L3

**Comment by ggerganov** [comment]
Yes, it is good - no worries

**Comment by 99991** [comment]
Excellent! Thank you!
