### ISSUE TITLE
pls update ggml models on https://huggingface.co/datasets/ggerganov/ggml/tree/main ,they have an outdated shape 😿 

### ISSUE THREAD

**Issue by mettemfurfur000** [ggerganov/ggml#87]
downloaded the converted model, changed the makefile to compile without avx (I have a really old processor + windows 10), and it has the wrong shape :cry:

![изображение](https://user-images.githubusercontent.com/94188324/232217677-eed903c3-de04-4db3-aeea-aa4257515d27.png)

the obvious answer appears: convert it by yourself! but I really cannot install torch and tensorflow on my machine, sorry... (I've been banging my head against the Internet for a week or so...)

It probably won't take much time to manually convert and update the repository, at least the smallest model! 

It will definitely save people time, because that's what that repository is for, isn't it?

love this project, have a nice day!😻

**Comment by ggerganov** [comment]
Should be good now
