### ISSUE TITLE
Build fails on Alpine Linux

### ISSUE THREAD

**Issue by EZForever** [ggerganov/ggml#903]
<https://github.com/ggerganov/ggml/commit/8a7be58d9f6c79c79025a3e396a14b8dc9669a5f> introduces a dependency on `execinfo.h`, which is not available (or rather, [removed](https://gitlab.alpinelinux.org/alpine/aports/-/commit/50795a14dee639ce2dcc836e2b2baca9bad4a1b1)) on Alpine Linux. This causes ggml and llama.cpp builds on Alpine to fail, as can be seen here: https://github.com/EZForever/llama.cpp-static/actions/runs/10128910987/job/28008339939

**Comment by slaren** [comment]
Feel free to open a PR to disable this functionality on Alpine.

**Comment by rahulmehtas** [comment]
It's a good question.

**Comment by EZForever** [comment]
Fixed in llama.cpp by ggerganov/llama.cpp#8783.
