### ISSUE TITLE
How much inaccuracy/difference from pytorch is to be expected?

### ISSUE THREAD

**Issue by chavinlo** [ggerganov/ggml#915]
Hello, a few weeks ago on #883 I was told that there was to be some slight difference from pytorch expected on ggml. However, I have been further porting the model (HuBERT) into ggml, and the difference continued growing and growing, and now after 30-ish "blocks" the difference is getting a bit concerning...

On the first block, `feature_extractor`, which is just 7 Conv1D, 1 Group Norm, and a few inplace GeLUs, the difference is very small but still acceptable:

GGML Output:
```text
dims: 928 512 1 1 f32
First & Last 10 elements:
0.00082 0.00127 0.00052 0.00166 0.00194 0.00228 0.00051 0.00063 0.00001 -0.00076
0.02071 -0.01569 0.00515 0.01100 -0.03571 -0.02370 -0.01015 -0.02249 -0.01920 -0.00361
sum:  -459.135949
```

Pytorch Output:
```text
dims: torch.Size([1, 512, 928]) torch.float32
First & Last 10 elements:
[0.00081, 0.00132, 0.00054, 0.0017, 0.00194, 0.00229, 0.00054, 0.00068, -1e-05, -0.00075]
[0.02066, -0.01545, 0.0053, 0.01141, -0.03561, -0.02357, -0.00955, -0.02235, -0.01908, -0.00314]
sum:  -459.71112060546875
```

On the second block, `layer_norm`, which is a norm layer with bias, outputs a difference thats a bit bigger from the first block:

GGML Output:
```text
dims: 512 928 1 1 f32
First & Last 10 elements:
-0.00148 -0.00114 -0.00298 -0.00375 -0.00304 -0.19735 -0.00158 -0.00227 0.15176 0.32282
-0.00708 -0.00236 -0.01410 0.02816 -0.00187 0.14543 -0.00118 -0.00185 -0.07328 0.10153
sum:  -11849.843736
```

Pytorch Output:
```text
dims: torch.Size([1, 928, 512]) torch.float32
First & Last 10 elements:
[-0.00148, -0.00114, -0.00298, -0.00376, -0.00304, -0.2042, -0.00158, -0.00227, 0.13578, 0.31828]
[-0.00707, -0.00236, -0.0141, 0.032, -0.00187, 0.14823, -0.00118, -0.00185, -0.07328, 0.11176]
sum:  -11980.99609375
```

The third block, `post_extract_proj`, is nothing more than a linear layer with bias, but the difference once again gets bigger:

GGML Output:
```text
dims: 768 928 1 1 f32
First & Last 10 elements:
0.23420 -0.04308 0.36195 -1.01714 -0.55842 -0.74043 -0.06722 0.16166 0.98925 0.90034
-3.91645 -0.41976 -0.30636 -0.56799 0.26271 -0.55689 0.38218 -0.14825 0.82683 -0.73491
sum:  -5578.222083
```
Pytorch Output:
```text
dims: torch.Size([1, 928, 768]) torch.float32
First & Last 10 elements:
[0.25546, -0.04067, 0.3587, -1.05641, -0.57509, -0.75408, -0.07237, 0.14982, 0.99075, 0.9247]
[-3.87562, -0.4089, -0.25278, -0.5513, 0.27736, -0.55433, 0.38134, -0.13394, 0.82322, -0.71393]
sum:  -5674.5029296875
```

Then, on the positional embedding section of the encoder block, the outputs are very, very different:

GGML Output:
```text
dims: 768 928 1 1 f32
First & Last 10 elements:
0.18384 0.43774 -0.01323 -0.04510 0.16553 0.17847 0.39526 0.16687 0.13611 0.01314
0.48682 0.12854 -0.14307 0.24927 -0.16003 0.05411 0.18164 -0.07831 0.01350 -0.16882
sum:  143483.242961
```

Pytorch Output:
```text
dims: torch.Size([1, 928, 768]) torch.float32
First & Last 10 elements:
[-0.1591, 0.17117, -0.16889, 0.45649, 0.66979, 0.61809, 0.08895, 0.23388, 0.49129, -0.16661]
[5.05966, 1.35264, 0.26677, -0.0, -0.0, 1.63973, 0.13964, 0.02565, 0.21715, -0.04758]
sum:  519205.15625
```

It could be because of my implementation of 1D Conv Groups (since I was unable to find any options to use groups in conv1d in ggml), but im not sure. I managed to take a screenshot from a moment where it did return a very close value to the Pytorch output, so at least it should be possible:
![devenv_GOMQQCwFul](https://github.com/user-attachments/assets/7618e059-fa07-4953-9108-e0a117deb893)
However, I didnt save a backup and moved the code to a git repo after I found out that the pos embed part was failing.

Here is the repository: https://github.com/chavinlo/rvc.cpp
It contains:
- The C++ GGML Inference code
- A notebook that has a simplified HuBERT, conversion to GGUF, and layer by layer inference so that you can see the outputs of each block (up to positional embedding)
- Links to weights for hubert both in pytorch and GGUF format in the notebook, or just https://huggingface.co/chavinlo/ggmltest

If more information is needed just lmk!

**Comment by Green-Sky** [comment]
At least the precision of GeLU should increase soon https://github.com/ggerganov/llama.cpp/pull/8878

**Comment by ggerganov** [comment]
The second block seems suspicious - make sure you use the correct epsilon value
