### ISSUE TITLE
[sync llama.cpp] Update ggml-sycl op

### ISSUE THREAD

**Issue by zhentaoyu** [ggerganov/ggml#916]
Hi @ggerganov and @slaren, do you have a plan to sync ggml repo with llama.cpp recently?  The [stabele-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp/pull/330) sycl backend needs a sycl op (https://github.com/ggerganov/llama.cpp/pull/8707) from ggml. I can help with it if you are too busy. Thanks.

cc @airMeng, @luoyu-intel

**Comment by ggerganov** [comment]
Yes, will sync later today

**Comment by ggerganov** [comment]
It should be synced now - let me know if there are any issues

**Comment by zhentaoyu** [comment]
It works great for me. Thanks a lot.
