### ISSUE TITLE
Please sync Vulkan from llama.cpp

### ISSUE THREAD

**Issue by SkutteOleg** [ggerganov/ggml#938]
https://github.com/ggerganov/llama.cpp/commit/0645ed5c97d0dc7c77c038fa966316ebc6c4bd65 this commit is required for Vulkan backend in [stable-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp)

**Comment by SkutteOleg** [comment]
I see it has been synced, but it's still missing this fix https://github.com/ggerganov/llama.cpp/commit/20f1789dfb4e535d64ba2f523c64929e7891f428 and dosn't build

**Comment by ggerganov** [comment]
It should build now

**Comment by SkutteOleg** [comment]
Unfortunately it doesn't build with Vulkan because [vulkan-shaders-gen.cpp](https://github.com/ggerganov/ggml/blob/master/src/vulkan-shaders/vulkan-shaders-gen.cpp) is missing these lines:
```diff
+    tasks.push_back(std::async(std::launch::async, [] {
+        string_to_spv("sin_f32", "sin.comp", {{"A_TYPE", "float"}, {"D_TYPE", "float"}, {"FLOAT_TYPE", "float"}});
+    }));
+
+    tasks.push_back(std::async(std::launch::async, [] {
+        string_to_spv("cos_f32", "cos.comp", {{"A_TYPE", "float"}, {"D_TYPE", "float"}, {"FLOAT_TYPE", "float"}});
+    }));
+
```

Which results in these errors:
```
D:\a\ggml\src\ggml-vulkan.cpp(1707,74): error C2065: 'sin_f32_len': undeclared identifier [D:\a\stable-diffusion.cpp\stable-diffusion.cpp\build\ggml\src\ggml.vcxproj]
D:\a\ggml\src\ggml-vulkan.cpp(1707,87): error C2065: 'sin_f32_data': undeclared identifier [D:\a\stable-diffusion.cpp\stable-diffusion.cpp\build\ggml\src\ggml.vcxproj]
D:\a\ggml\src\ggml-vulkan.cpp(1708,74): error C2065: 'cos_f32_len': undeclared identifier [D:\a\stable-diffusion.cpp\stable-diffusion.cpp\build\ggml\src\ggml.vcxproj]
D:\a\ggml\src\ggml-vulkan.cpp(1708,87): error C2065: 'cos_f32_data': undeclared identifier [D:\a\stable-diffusion.cpp\stable-diffusion.cpp\build\ggml\src\ggml.vcxproj]
```

This was fixed in https://github.com/ggerganov/llama.cpp/commit/20f1789dfb4e535d64ba2f523c64929e7891f428, but the same fix but doesn't exist in ggml

**Comment by ggerganov** [comment]
Should be good now. Please give it a try

**Comment by SkutteOleg** [comment]
All good, thanks!
