### ISSUE TITLE
Need StableLM support 

### ISSUE THREAD

**Issue by faisalhr1997** [ggerganov/ggml#94]
https://github.com/Stability-AI/StableLM

**Comment by faisalhr1997** [comment]
![Screenshot_2023-04-19-22-43-58-451_com.github.android.png](https://user-images.githubusercontent.com/97628039/233143915-86a6f965-2bbc-4d15-8626-dc088da29cf4.png)

**Comment by ggerganov** [comment]
https://github.com/ggerganov/ggml/tree/master/examples/stablelm
