### ISSUE TITLE
Find file gguf

### ISSUE THREAD

**Issue by FahNos** [ggerganov/ggml#985]
Hi, I am newbie
I want to run file mnist-train-fc.py, but have import gguf and I can not find it.
Could you guide me where the file gguf

Thank you

**Comment by JohannesGaessler** [comment]
Did you follow the setup steps in the README for setting up a Python environment?

**Comment by FahNos** [comment]
Dear sir
I followed the setup
I only want to run file mnist-train-fc.py, and cant find gguf.
Normally file gguf.py must have somewhere in repo, but I cant file it

**Comment by JohannesGaessler** [comment]
gguf is a Python package. It's not in this repository, it's supposed to be installed via pip.
